name: amplify_native_legacy_wrapper_example
description: Demonstrates how to use the amplify_native_legacy_wrapper plugin.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  amplify_native_legacy_wrapper: ^0.1.0

dev_dependencies:
  amplify_lints:
    path: ../../../amplify_lints
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
