# Validates that PR titles follow conventional commits
name: "PR Title Lint"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
        # amannn/action-semantic-pull-request@4.5
      - uses: amannn/action-semantic-pull-request@6a7ed2d5046cf8a40c60494c83c962343061874a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
