name: Verify Pub Constraints
on:
  schedule:
    - cron: "0 13 * * *" # Every day at 06:00 PST

jobs:
  test:
    name: Verify Pub Constraints
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # 4.1.0
        with:
          submodules: true

      - name: Setup Flutter
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # 2.10.0
        with:
          cache: true
          channel: stable

      - name: Setup aft
        run: dart pub global activate -spath packages/aft

      - name: Verify Pub Constraints
        run: aft constraints pub-verify
