name: Verify Pub Constraints
on:
  schedule:
    - cron: "0 13 * * *" # Every day at 06:00 PST

jobs:
  test:
    name: Verify Pub Constraints
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
        with:
          submodules: true

      - name: Setup Flutter
        uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1 # 2.16.0
        with:
          cache: true
          channel: stable

      - name: Setup aft
        run: dart pub global activate -spath packages/aft

      - name: Verify Pub Constraints
        run: aft constraints pub-verify
